server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_catalog_db
    username: yourUsername
    password: yourPassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: ecommerce-catalog-service
